apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.name" . | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app.kubernetes.io/instance: {{ include "app.revision" . | quote }}
    app.kubernetes.io/part-of: rse
    {{- include "app.istioLabels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "app.labels" . | nindent 8 }}
      annotations:
        {{- include "app.metricsAnnotations" . | nindent 8 }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}

    spec:
      securityContext:
        {{- include "app.securitycontext" . | nindent 8 }}

      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        - name: {{ . | quote }}
      {{- end }}

      containers:
        - name: {{ include "app.name" . }}
          image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}

          {{- if .Values.useSecretRef }}
          envFrom:
            - secretRef:
                name: {{ .Values.secretRefName | quote }}

          {{- else if .Values.useConfigMap }}
          envFrom:
            - configMapRef:
                name: {{ .Values.configMapName | quote }}

          {{- else }}
          env:
            {{- $podAnnotations := default dict .Values.podAnnotations }}
            {{- $injectionEnabled := eq (default "false" (index $podAnnotations "inject.xfsc.io/enabled")) "true" }}

            {{- if not $injectionEnabled }}
            - name: SDJWT_SERVICE_URL
              value: {{ .Values.signer.sdjwt.url | quote }}

            {{- with .Values.signer.nats }}
            - name: NATS_HOST
              value: {{ .natsHost | quote }}

            - name: NATS_TOPIC
              value: {{ .topic | quote }}
            {{- end }}
            {{- end }}

            - name: CRYPTO_GRPC_ADDR
              value: {{ .Values.signer.engine.clusterAddress | quote }}

            - name: VERSION
              value: {{ .Values.signer.version | quote }}

            - name: LOG_LEVEL
              value: {{ .Values.log.level | default "INFO" | quote }}

            - name: LOG_ENCODING
              value: {{ .Values.log.encoding | default "json" | quote }}

            - name: HTTP_HOST
              value: {{ .Values.signer.http.host | quote }}

            - name: HTTP_PORT
              value: {{ .Values.signer.http.port | quote }}

            - name: HTTP_IDLE_TIMEOUT
              value: {{ .Values.signer.http.timeout.idle | quote }}

            - name: HTTP_READ_TIMEOUT
              value: {{ .Values.signer.http.timeout.read | quote }}

            - name: HTTP_WRITE_TIMEOUT
              value: {{ .Values.signer.http.timeout.write | quote }}

            {{- with .Values.signer.policy }}
            {{- with .serviceEndpointPolicy }}
            - name: SERVICE_POLICY
              value: {{ . | quote }}
            {{- end }}

            {{- with .termsOfUsePolicy }}
            - name: TERMSOFUSE_POLICY
              value: {{ . | quote }}
            {{- end }}
            {{- end }}

            {{- range $key, $value := .Values.secretEnv }}
            - name: {{ $key | quote }}
              valueFrom:
                secretKeyRef:
                  name: {{ $value.name | quote }}
                  key: {{ $value.key | quote }}
            {{- end }}

            {{- with .Values.extraVars }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}

          ports:
            {{- if .Values.metrics.enabled }}
            - name: monitoring
              containerPort: {{ .Values.metrics.port }}
            {{- end }}

            - name: http
              containerPort: {{ .Values.signer.http.port }}

          readinessProbe:
            httpGet:
              path: /readiness
              port: {{ .Values.signer.http.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 2
            failureThreshold: 2
            timeoutSeconds: 5

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

        - name: {{ printf "%s-crypto-engine" (include "app.name" .) }}
          image: {{ .Values.signer.engine.image | quote }}

          env:
            - name: CRYPTO_GRPC_ADDR
              value: {{ .Values.signer.engine.address | quote }}

            {{- range $key, $value := .Values.signer.engine.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}

            {{- range $key, $value := .Values.signer.engine.secretEnv }}
            - name: {{ $key | quote }}
              valueFrom:
                secretKeyRef:
                  name: {{ $value.name | quote }}
                  key: {{ $value.key | quote }}
            {{- end }}